package com.platescanner.app.data

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Persisted plate record. This is the canonical shape used across the data,
 * UI, and export layers.
 *
 * - [id] auto-generated by Room.
 * - [plate] is the canonical plate text.
 * - [capturedAt] is wall-clock ms since epoch when the frame was captured.
 * - [thumbnailPath] is an absolute file path on the device, or null.
 * - [confidence] is 0f..1f, or null if the backend didn't return one.
 */
@Entity(tableName = "plate_records")
data class PlateRecord(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0L,
    @ColumnInfo(name = "plate")
    val plate: String,
    @ColumnInfo(name = "captured_at")
    val capturedAt: Long,
    @ColumnInfo(name = "thumbnail_path")
    val thumbnailPath: String? = null,
    @ColumnInfo(name = "confidence")
    val confidence: Float? = null,
)
